# ****************************************************** Scenario: Ansible Unarchive Module ********************************************************

# One of the DevOps team members has created an ZIP archive on jump host in Stratos DC that needs to be extracted and copied over to all app servers in Stratos DC itself. Because this is a routine task, the Nautilus DevOps team has suggested automating it. We can use Ansible since we have been using it for other automation tasks. Below you can find more details about the task:

# We have an inventory file under /home/thor/ansible directory on jump host, which should have all the app servers added already.

# There is a ZIP archive /usr/src/dba/datacenter.zip on jump host.

# Create a playbook.yml under /home/thor/ansible/ directory on jump host itself to perform the below given tasks.

# Unzip /usr/src/dba/datacenter.zip archive in /opt/dba/ location on all app servers.

# Make sure the extracted data must has the respective sudo user as their user and group owner, i.e tony for app server 1, steve for app server 2, banner for app server 3.

# The extracted data permissions must be 0777

# Note: Validation will try to run the playbook using command ansible-playbook -i inventory playbook.yml so please make sure playbook works this way, without passing any extra arguments.

# -------------------------------------------------------------------------------------------------------------------------------------------
# Solution:

# 1. Go through the folder mentioned in task and create inventory & playbook files

# 2. Check the existing file & verify the inventory file    
# ansible all -a 'ls -lrt /opt/dba/' -i inventory

# 3.  Create a playbook as per the task
# vi playbook.yml

- name: extract and archive playbook
  hosts: all
  become: true
  tasks:
  - name: extract the archie and set the permissions in all app servers
    unarchive:
	  src: /usr/src/dba/datacenter.zip
	  dest: /opt/dba/
	  owner: "{{ ansible_user }}"
	  group: "{{ ansible_user }}"
	  mode: "0655"
	  
# 4. Post file saved , run below command to execute the playbook 
	 
# ansible-playbook -i inventory playbook.yml --syntax-check
# ansible-playbook -i inventory playbook.yml --check
# ansible-playbook -i inventory playbook.yml

# 5. validate the task by running the below command
# ansible all -a 'ls -lrt /opt/dba/' -i inventory



    
    

