# ***************************************    Scenario: Ansible File Module **************************************************************
# The Nautilus DevOps team is working to test several Ansible modules on servers in Stratos DC. 
# Recently they wanted to test file creation on remote hosts using Ansible. More details about the task aregiven below. Please proceed with the same:

# a. Create an inventory file ~/playbook/inventory on jump host and add all app servers in it.

# b. Create a playbook ~/playbook/playbook.yml to create a blank file /opt/appdata.txt on all app servers.

# c. The /opt/appdata.txt file permission must be 0744.

# d. The user/group owner of file /opt/appdata.txt must be tony on app server 1, steve on app server 2 and banner on app server 3.

# Note: Validation will try to run playbook using command ansible-playbook -i inventory playbook.yml, so please make sure playbook works this way, without passing any extra arguments.

# -----------------------------------------------------------------------------------------------------------------------------------------
# 1. create inventory file
 
# vi ~/playbook/inventory
 
# stapp01  ansible_host=172.16.238.10   ansible_connection=ssh   ansible_user=tony  ansible_ssh_pass=Ir0nM@n
# stapp02  ansible_host=172.16.238.11   ansible_connection=ssh   ansible_user=steve ansible_ssh_pass=Am3ric@
# stapp03  ansible_host=172.16.238.12   ansible_connection=ssh   ansible_user=banner ansible_ssh_pass=BigGr33n


# 2. create playbook

# vi ~/playbook/playbook.yml

---
- name: KKE Copy File playbook
  hosts: all
  become: yes
  tasks:
   - name: create blank file in all app servers
     copy:
	  content: ""
	  dest: /opt/appdata.txt
	  owner: "{{ ansible_user }}"
	  group: "{{ ansible_user }}"
	  mode: 0744
	  
#	       (OR)
   - name: create blank file in all app servers
     file:
	  path: /opt/appdata.txt
	  owner: "{{ ansible_user }}"
	  group: "{{ ansible_user }}"
	  mode: 0744
      state: touch	  
...	  

# 3. Test the changes
# ansible-playbook -i inventory playbook.yml --syntax-check
# ansible-playbook -i inventory playbook.yml --check
# ansible-playbook -i inventory playbook.yml

