# ********************************************Scenario: Managing Jinja2 Templates Using Ansible **********************************

# One of the Nautilus DevOps team members is working to develop a role for httpd installation and configuration. Work is almost completed, however there is a requirement to add a jinja2 template for index.html file. Additionally, the relevant task needs to be added inside the role. The inventory file ~/ansible/inventory is already present on jump host that can be used. Complete the task as per details mentioned below:

# a. Update ~/ansible/playbook.yml playbook to run the httpd role on App Server 1.

# b. Create a jinja2 template index.html.j2 under /home/thor/ansible/role/httpd/templates/ and add a line This file was created using Ansible on <respective server> (for example This file was created using Ansible on stapp01 in case of App Server 1). Also please make sure not to hard code the server name inside the template. Instead, use inventory_hostname variable to fetch the correct value.

# c. Add a task inside /home/thor/ansible/role/httpd/tasks/main.yml to copy this template on App Server 1 in /var/www/html/index.html. Also make sure that /var/www/html/index.html file permissions 0644.

# d. The user/group owner of /var/www/html/index.html file must be respective sudo user of server (for example tony in case of stapp01).

# Note: Validation will try to run playbook using command ansible-playbook -i inventory playbook.yml so please make sure playbook works this way, without passing any extra arguments.

#---------------------------------------------------------------------------------------------------------------------------------------------
# Solution:
#a: update the inventory to use app1a server

# vi playbook.yml
- hosts: app1a

# b: create jinja2 template and add the line

# vi ~/ansible/role/httpd/templates/index.html.j2

# This file was created using Ansible on {{ inventory_hostname }}

# c & d: add task to use template and give permissions as per the questions

# vi ~/ansible/role/httpd/tasks/main.yml

- name: copy template file and grant permissions
  template:
   src: index.html.j2
   dest: /var/www/html/index.html
   owner: "{{ ansible_user }}"
   group: "{{ ansible_user }}"
   mode: "0644"
   
#Test the changes:

#1. execute below steps
#ansible-playbook -i inventory playbook.yml --syntax-check
#ansible-playbook -i inventory playbook.yml --check   

#2. login app1a and execute below steps

#systemctl status httpd
#check the owner/group of index.html file
#cd /var/www/html/index.html
