# **************************************************** Scenario: Ansible Facts Gathering **********************************************************

# The Nautilus DevOps team is trying to setup a simple Apache web server on all app servers in Stratos DC using Ansible. They also want to create a sample html page for now with some app specific data on it. Below you can find more details about the task.

# You will find a valid inventory file /home/thor/playbooks/inventory on jump host (which we are using as an Ansible controller).

# Create a playbook index.yml under /home/thor/playbooks directory on jump host. Using blockinfile Ansible module create a file facts.txt under /root directory on all app servers and add the following given block in it. You will need to enable facts gathering for this task.

# Ansible managed node IP is <default ipv4 address>

# (You can obtain default ipv4 address from Ansible's gathered facts by using the correct Ansible variable while taking into account Jinja2 syntax)

# Install httpd server on all apps. After that make a copy of facts.txt file as index.html under /var/www/html directory. Make sure to start httpd service after that.
# Note: Do not create a separate role for this task, just add all of the changes in index.yml playbook.

# -------------------------------------------------------------------------------------------------------------------------------------------
# Solutions:

# 1. At first ansible inventory file is working properly and doesn't have any file exist from jump server to all the app server's 
# ansible all -a 'ls -lrt /root/' -i inventory

# 2. Create playbook based on the specifications

- name: text file playbook
  hosts: all
  become: true
  gather_facts: yes
  become_method: sudo
  tasks:
  - name: create a file in all servers using blockinfile
    blockinfile:
	create: yes
    path: /root/facts.txt
    block: |
      Ansible managed node IP is {{ ansible_host }}

  - name: Install httpd server
    yum:
     name: httpd
     state: latest
   
  - name: ensure httpd is running
    service:
      name: httpd 
      state: started   
   
  - name: Copy index.html file
    copy:   
     src: /root/facts.txt
     dest: /var/www/html/index.html
     remote_src: yes
   
# 3.  Post file saved , run below command to execute the playbook 
# ansible-playbook -i inventory playbook.yml --syntax-check
# ansible-playbook -i inventory playbook.yml --check
# ansible-playbook -i inventory playbook.yml

# 4.  Validate the task by below command 
# ansible all -a 'ls -lrt /root/' -i inventory

