# ****************************************** Scenario: Creating Soft Links Using Ansible ************************************************

# The Nautilus DevOps team is practicing some of the Ansible modules and creating and testing different Ansible playbooks to accomplish tasks.

# Recently they started testing an Ansible file module to create soft links on all app servers. Below you can find more details about it.

# Write a playbook.yml under /home/thor/ansible directory on jump host, an inventory file is already present under /home/thor/ansible directory on jump host itself. Using this playbook accomplish below given tasks:

# Create an empty file /opt/dba/blog.txt on app server 1; its user owner and group owner should be tony. Create a symbolic link of source path /opt/dba to destination /var/www/html.

# Create an empty file /opt/dba/story.txt on app server 2; its user owner and group owner should be steve. Create a symbolic link of source path /opt/dba to destination /var/www/html.

# Create an empty file /opt/dba/media.txt on app server 3; its user owner and group owner should be banner. Create a symbolic link of source path /opt/dba to destination /var/www/html.

# Note: Validation will try to run the playbook using command ansible-playbook -i inventory playbook.yml so please make sure playbook works this way without passing any extra arguments.

# -----------------------------------------------------------------------------------------------------------------------------------------
# Solution:

# 1. At first ansible inventory file is working properly and doesn't have any file exist from jump server to all the app server's 
# ansible all -a 'ls -lrt /opt/dba/' -i inventory
# ansible all -a 'ls -lrt /var/www/html/' -i inventory

# 2. Create playbook based on the specifications
- name: Create file and set ACL in Host 1
  hosts: stapp01
  become: yes
  tasks:
  - name: Create empty file in Server-1
    file:
      path: "/opt/dba/blog.txt"
      owner: "{{ ansible_user }}"
	  group: "{{ ansible_user }}"
	  state: touch
  - name: Create symbolic link 
    file:
     src: "/opt/dba"
     dest: "/var/www/html"
     state: link

- name: Create file and set ACL in Host 2
  hosts: stapp02
  become: yes
  tasks:
  - name: Create empty file in Server-2
    file:
      path: "/opt/dba/story.txt"
      owner: "{{ ansible_user }}"
	  group: "{{ ansible_user }}"
	  state: touch
  - name: Create symbolic link 
    file:
     src: "/opt/dba"
     dest: "/var/www/html"
     state: link

- name: Create file and set ACL in Host 3
  hosts: stapp03
  become: yes
  tasks:
  - name: Create empty file in Server-3
    file:
      path: "/opt/dba/media.txt"
      owner: "{{ ansible_user }}"
	  group: "{{ ansible_user }}"
	  state: touch
  - name: Create symbolic link 
    file:
     src: "/opt/dba"
     dest: "/var/www/html"
     state: link	
	 
# 3.  Post file saved , run below command to execute the playbook 
# ansible-playbook -i inventory playbook.yml --syntax-check
# ansible-playbook -i inventory playbook.yml --check
# ansible-playbook -i inventory playbook.yml

# 4.  Validate the task by below command 
# ansible all -a 'ls -lrt /opt/dba/' -i inventory
# ansible all -a 'ls -lrt /var/www/html/' -i inventory

