# *********************************************** Scenario: Managing ACLs Using Ansible *********************************************************

# There are some files that need to be created on all app servers in Stratos DC. The Nautilus DevOps team want these files to be owned by user root only however, they also want that the app specific user to have a set of permissions on these files. All tasks must be done using Ansible only, so they need to create a playbook. Below you can find more information about the task.

# Create a playbook.yml under /home/thor/ansible on jump host, an inventory file is already present under /home/thor/ansible directory on Jump Server itself.

# Create an empty file blog.txt under /opt/dba/ directory on app server 1. Set some acl properties for this file. Using acl provide read '(r)' permissions to group tony (i.e entity is tony and etype is group).

# Create an empty file story.txt under /opt/dba/ directory on app server 2. Set some acl properties for this file. Using acl provide read + write '(rw)' permissions to user steve (i.e entity is steve and etype is user).

# Create an empty file media.txt under /opt/dba/ on app server 3. Set some acl properties for this file. Using acl provide read + write '(rw)' permissions to group banner (i.e entity is banner and etype is group).

# Note: Validation will try to run the playbook using command ansible-playbook -i inventory playbook.yml so please make sure the playbook works this way, without passing any extra arguments.

# ------------------------------------------------------------------------------------------------------------------------------------------
# Solution:

# 1. At first ansible inventory file is working properly and doesn't have any file exist from jump server to all the app server's 
# ansible all -a 'ls -lrt /root/' -i inventory

# 2. Create playbook based on the specifications

- name: Create file and set ACL in Host 1
  hosts: stapp01
  become: yes
  tasks:
    - name: Create the blog.txt on stapp01
      file:
        path: /opt/dba/blog.txt
        state: touch

    - name: Set ACL for blog.txt
      acl:
        path: /opt/dba/blog.txt
        entity: "{{ ansible_user }}"
        etype: group
        permissions: r
        state: present

- name: Create file and set ACL in Host 2
  hosts: stapp02
  become: yes
  tasks:
    - name: Create the story.txt on stapp02
      file:
        path: /opt/dba/story.txt
        state: touch

    - name: Set ACL for story.txt
      acl:
        path: /opt/dba/story.txt
        entity: "{{ ansible_user }}"
        etype: user
        permissions: rw
        state: present

- name: Create file and set ACL in Host 3
  hosts: stapp03
  become: yes
  tasks:
    - name: Create the media.txt on stapp03
      file:
        path: /opt/dba/media.txt
        state: touch

    - name: Set ACL for media.txt
      acl:
        path: /opt/dba/media.txt
        entity: "{{ ansible_user }}"
        etype: group
        permissions: rw
        state: present
		
# 3.  Post file saved , run below command to execute the playbook 
# ansible-playbook -i inventory playbook.yml --syntax-check
# ansible-playbook -i inventory playbook.yml --check
# ansible-playbook -i inventory playbook.yml

# 4.  Validate the task by below command 
# ansible all -a 'ls -lrt /root/dba' -i inventory

